name: Connect to GCP

on:
  push:
    branches:
      - main

jobs:
  connect-gcp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Authenticate with GCP
        uses: actions/setup-gcloud@v2
        with:
          client-id: ${{ secrets.GCP_CLIENT_ID }}
          client-secret: ${{ secrets.GCP_CLIENT_SECRET }}
          scopes: "https://www.googleapis.com/auth/cloud-platform"
      - name: List GCP projects
        run: gcloud projects list
